/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    Grid: typeof import('./../components/Grid/index.vue')['default']
    GridItem: typeof import('./../components/Grid/components/GridItem.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    IEpCaretBottom: typeof import('~icons/ep/caret-bottom')['default']
    IEpCaretTop: typeof import('~icons/ep/caret-top')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Pagination: typeof import('./../components/SimpleTable/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFormDatePicker: typeof import('./../components/SearchForm/modules/SchemaFormDatePicker.vue')['default']
    SchemaFormInput: typeof import('./../components/SearchForm/modules/SchemaFormInput.vue')['default']
    SchemaFormSelect: typeof import('./../components/SearchForm/modules/SchemaFormSelect.vue')['default']
    SearchForm: typeof import('./../components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./../components/SearchForm/components/SearchFormItem.vue')['default']
    SimpleTable: typeof import('./../components/SimpleTable/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./../components/SimpleTable/components/TableColumn.vue')['default']
    TreeFilter: typeof import('./../components/TreeFilter/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
